#cloud-config
package_update: false
packages: 
  - python-pip
timezone: Australia/Sydney

write_files:
# setup script
  - path: "/root/bastion/bastion.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${bastion_sh_content}
  - path: "/root/.oci/config"
    permissions: "0400"
    encoding: "gzip+base64"
    content: |
      ${oci_config_content}
  - path: "/root/.ssh/oci_rsa.pem"
    permissions: "0400"
    encoding: "gzip+base64"
    content: |
      ${api_private_key_content}            
runcmd:
 - echo "Configuring bastion..." | tee /root/bastion/bastion.txt
 - /root/bastion/bastion.sh
 - pip install oci-cli --upgrade
 - touch /home/opc/bastion.finish